version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    environment:
      PORT: 3000
      DATABASE_URI: mongodb://test:password@localhost:27017
    ports:
      - "3000:3000"
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - /usr/src/app/node_modules
      - /usr/src/app/packages/api/node_modules
    command: yarn start:dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
